#!/usr/bin/env python3
"""
generate_test_data.py
─────────────────────
Reads up to NUM_SAMPLES HDF5 files from HDF_DIR and emits test_data.h,
a C header that embeds spike frames for STM32 SNN validation.

HDF5 file layout expected (as produced by ST-MNIST pipeline):
  data/0   – int16  (T, CH, H, W)   spike counts per pixel per timestep
  target/0 – int64  scalar           ground-truth class label (0-9)

Usage:
  pip install h5py numpy
  python3 generate_test_data.py --hdf_dir ./cache/stmnist/test/ --num_samples 200 --out test_data_200.h
  
File naming convention assumed: {index}_0.hdf5  (e.g. 0_0.hdf5 … 49_0.hdf5)
If your files use a different pattern, adjust the glob below.
"""

import os
import sys
import argparse
import numpy as np

try:
    import h5py
except ImportError:
    sys.exit("h5py not found – run: pip install h5py numpy")

# ── CLI ──────────────────────────────────────────────────────────────────────
parser = argparse.ArgumentParser(description="Generate test_data.h from ST-MNIST HDF5 files")
parser.add_argument("--hdf_dir",     default=".",        help="Directory containing *_0.hdf5 test files")
parser.add_argument("--num_samples", type=int, default=50, help="How many samples to embed (default 50)")
parser.add_argument("--out",         default="test_data.h", help="Output header filename")
args = parser.parse_args()

HDF_DIR     = args.hdf_dir
NUM_SAMPLES = args.num_samples
OUT_FILE    = args.out

# ── Collect files ─────────────────────────────────────────────────────────────
candidate_paths = []
for idx in range(NUM_SAMPLES * 20):          # search wider range in case gaps exist
    p = os.path.join(HDF_DIR, f"{idx}_0.hdf5")
    if os.path.exists(p):
        candidate_paths.append((idx, p))
    if len(candidate_paths) == NUM_SAMPLES:
        break

if not candidate_paths:
    sys.exit(f"No *_0.hdf5 files found in '{HDF_DIR}'. Check --hdf_dir.")

if len(candidate_paths) < NUM_SAMPLES:
    print(f"Warning: only found {len(candidate_paths)} files (requested {NUM_SAMPLES}).")
    NUM_SAMPLES = len(candidate_paths)

print(f"Embedding {NUM_SAMPLES} samples from '{HDF_DIR}' → '{OUT_FILE}'")

# ── Load samples ──────────────────────────────────────────────────────────────
NUM_INPUTS = 200   # 2 * 10 * 10

samples = []          # list of (flat_int8 [T,200], label, T, original_file_idx)
for file_idx, path in candidate_paths:
    with h5py.File(path, "r") as f:
        raw   = np.array(f["data/0"])           # (T, CH, H, W)  int16
        label = int(f["target/0"][()])
    T, CH, H, W = raw.shape
    assert CH * H * W == NUM_INPUTS, \
        f"{path}: expected CH*H*W={NUM_INPUTS}, got {CH}*{H}*{W}={CH*H*W}"
    flat = np.clip(raw, -128, 127).astype(np.int8).reshape(T, NUM_INPUTS)
    samples.append((flat, label, T, file_idx))
    print(f"  [{file_idx:4d}_0.hdf5]  T={T:3d}  label={label}")

# ── Emit header ───────────────────────────────────────────────────────────────
lines = []

lines += [
    "/*",
    f" * {OUT_FILE} — Auto-generated by generate_test_data.py",
    " * ST-MNIST spike test-vectors for STM32 SNN inference validation.",
    " *",
    " * Layout per sample:",
    " *   spikes[t][i]  — q7_t spike value for input i at timestep t",
    " *                   (values 0-17; non-zero = active spike)",
    " *   num_timesteps — how many frames the gesture spans",
    " *   label         — ground-truth class (0-9)",
    " *",
    " * Re-generate:  python3 generate_test_data.py --hdf_dir <dir> --num_samples 50",
    " */",
    "",
    "#ifndef TEST_DATA_H",
    "#define TEST_DATA_H",
    "",
    "#include <stdint.h>",
    "",
    "/* ── Constants ──────────────────────────────────────── */",
    "#define TD_NUM_INPUTS    200   /* CH * H * W = 2 * 10 * 10 */",
    "#define TD_NUM_CLASSES   10",
    f"#define TD_NUM_SAMPLES   {NUM_SAMPLES}",
    "",
    "/* ── Per-sample descriptor ───────────────────────────── */",
    "typedef struct {",
    "    const int8_t  (*spikes)[TD_NUM_INPUTS]; /* [timestep][input_idx] */",
    "    uint16_t       num_timesteps;",
    "    uint8_t        label;                   /* ground-truth class 0-9 */",
    "} TestSample;",
    "",
]

# Spike arrays (one static array per sample)
for embed_idx, (flat, label, T, file_idx) in enumerate(samples):
    lines.append(f"/* ── Sample {embed_idx}  (file {file_idx}_0.hdf5)  label={label}  T={T} ── */")
    lines.append(f'__attribute__((section(".ext_weights")))') # I put test data inside of the QSPI. 
    lines.append(f"static const int8_t _spikes_{embed_idx}[{T}][TD_NUM_INPUTS] = {{")
    for t in range(T):
        row   = ", ".join(f"{int(v):4d}" for v in flat[t])
        trail = "," if t < T - 1 else " "
        lines.append(f"    {{{row}}}{trail} /* t={t} */")
    lines.append("};")
    lines.append("")

# Lookup table
lines += [
    "/* ── Sample table (size TD_NUM_SAMPLES) ─────────────── */",
    "static const TestSample test_samples[TD_NUM_SAMPLES] = {",
]
for embed_idx, (flat, label, T, file_idx) in enumerate(samples):
    trail = "," if embed_idx < NUM_SAMPLES - 1 else " "
    lines.append(
        f"    {{ _spikes_{embed_idx}, {T:3d}, {label} }}{trail}"
        f"  /* sample {embed_idx}: file {file_idx}_0.hdf5 */"
    )
lines += [
    "};",
    "",
    "#endif /* TEST_DATA_H */",
    "",
]

with open(OUT_FILE, "w") as f:
    f.write("\n".join(lines))

print(f"\nDone → {OUT_FILE}  ({os.path.getsize(OUT_FILE)//1024} KB)")
